---
title: "Final_Project_Data_Manip"
output: html_notebook
---
NEED LAT LONG FROM SPEC DATA 
```{r}
library(tidyverse)
library(tibble)
load("spec_net.Rdata")
load("veg.Rdata")
```

```{r}
#cleaning data

# from [spec.data](http://spec.data) 
# 
# - drop: col 4:9, col 12:36 col 39:43 col 45:61, 63, 65:80, 82:83, 85:124, 128:148, 152:156, 
# - spec interaction-> WANT col 62 ="degree", 64 = "species.strength" 81 = "d" 84 = "rare.degree", 125 =  "SiteBeeAbundance" 126 = "SiteBeeRichness", 127=  "SiteBeeDiversity" 149 = "PollRichness" 150 = "PollAbundance" 151 = "PollDiversity", 157 = "VegAbundance", 158 = "VegRichness",  159 = "VegDiversity"
#lat = col 37, long = col 38
clean_spec.net <- spec.net %>%
  select("Site","SampleRound","Year", "GenusSpecies" ,"PlantGenusSpecies","species.strength", "d", "rare.degree", "SiteBeeAbundance", "SiteBeeRichness", "SiteBeeDiversity", "PollRichness", "PollAbundance","PollDiversity","VegAbundance", "VegRichness", "VegDiversity", "Lat", "Long")
    
    #-c(4:9, 12:36, 39:43, 45:61, 63, 65:80, 82:83, 85:124, 128:148, 152:156))
#from veg
#drop: col 1:6, 
clean_veg <- veg %>%
  select(-c(1:6))

```


```{r}
# GenusSpecies from spec.net (pollinators)
native_poll <- c("Bombus mixtus", "Bombus melanopygus", "Bombus vosnesenskii",
                    "Bombus vancouverensis", "Bombus griseocollis", "Bombus californicus",
                    "Bombus appositus", "Bombus insularis", "Bombus nevadensis",
                    "Bombus occidentalis", "Bombus flavifrons", "Bombus fernaldae",
                    "Bombus suckleyi", "Bombus morrisoni", "Bombus sitkensis",
                    "Colletes simulans", "Osmia sp.", "Chelostoma phaceliae",
                    "Hoplitis fulgida", "Hoplitis albifrons", "Hoplitis producta",
                    "Megachile perihirta", "Megachile melanophaea", "Megachile brevis",
                    "Megachile pugnata", "Megachile fidelis", "Megachile relativa",
                    "Megachile angelarum", "Megachile subnigra", "Megachile mellitarsis",
                    "Halictus rubicundus", "Halictus tripartitus", "Halictus farinosus",
                    "Halictus ligatus", "Halictus confusus", "Lasioglossum titusi",
                    "Lasioglossum nevadense", "Lasioglossum cordleyi", "Lasioglossum olympiae",
                    "Andrena pertristis", "Andrena vicinoides", "Andrena columbiana",
                    "Andrena scutellinitens", "Andrena nigrocaerulea", "Andrena prunorum",
                    "Andrena melanochroa", "Andrena topazana", "Andrena cupreotincta",
                    "Agapostemon virescens", "Xylocopa californica", "Ceratina acantha",
                    "Ceratina nanula", "Melissodes rivalis", "Melissodes microstictus",
                    "Nomada sp.", "Sphecodes sp.", "Dufourea calochorti", "Dufourea versatilis",
                    "Dufourea campanulae", "Anthidium mormonum", "Anthidium utahense")

non_native_poll <- c("Apis mellifera", "Anthidium manicatum")

#PlantGenusSpecies from veg (plants)
native_veg <- c("Delphinium menziesii", "Aquilegia formosa", "Collinsia parviflora",
                "Vicia americana", "Lupinus laxiflorus", "Achillea millefolium",
                "Angelica arguta", "Erysimum capitatum", "Senecio integerrimus",
                "Ligusticum grayi", "Polemonium carneum", "Solidago canadensis",
                "Cirsium callilepis", "Eriophyllum lanatum", "Mimulus rubellus",
                "Gayophytum humile", "Potentilla gracilis", "Lewisia triphylla",
                "Gilia capitata", "Phlox gracilis", "Lathyrus nevadensis",
                "Eriogonum compositum", "Castilleja hispida", "Zigadenus venenosus",
                "Eriogonum umbellatum", "Epilobium oregonense", "Phacelia hastata",
                "Penstemon procerus", "Rosa gymnocarpa", "Symphoricarpos mollis",
                "Mimulus guttatus", "Berberis aquifolium", "Sedum oregonense",
                "Fragaria virginiana", "Arctostaphylos nevadensis", "Madia minima",
                "Holodiscus discolor", "Rubus parviflorus", "Tiarella trifoliata",
                "Viola glabella", "Galium oreganum", "Rainiera stricta",
                "Trillium ovatum", "Vaccinium membranaceum", "Lupinus latiflorus",
                "Iris chrysophylla", "Dichelostemma congestum", "Chamerion angustifolium",
                "Erythronium grandiflorum", "Xerophyllum tenax", "Lupinus polyphyllus",
                "Phacelia nemoralis", "Ceanothus velutinus", "Tolmiea menziesii",
                "Lilium columbianum", "Sedum oreganum", "Sorbus sitchensis",
                "Mahonia nervosa", "Ranunculus uncinatus", "Nemophila parviflora",
                "Ribes viscosissimum")

# Non-native plants from veg data 
non_native_veg <- c("Rumex acetosella", "Hypericum perforatum", "Taraxacum officinale",
                    "Galium aparine", "Cerastium arvense", "Vicia sativa",
                    "Prunella vulgaris", "Chrysanthemum leucanthemum",
                    "Hypochaeris radicata", "Veronica serpyllifolia")
```

```{r}
#and col with mutate for non-native with spec.net

clean_spec.net <- clean_spec.net %>%
  mutate(non_native_plant= ifelse(PlantGenusSpecies %in% non_native_veg, "non-native", "native"),
         non_native_bee= ifelse(GenusSpecies %in% non_native_poll, "non-native", "native"))

unique(clean_spec.net$PlantGenusSpecies[clean_spec.net$non_native_plant == "non-native"])
unique(clean_spec.net$GenusSpecies[clean_spec.net$non_native_bee == "non-native"])


```


```{r}
#creating spacial data frame to plot onto satellite imagery 
spacial_df <- clean_spec.net[, c("Lat", "Long", "non_native_plant", "Year","Site")]%>%
  filter(non_native_plant== "non-native")%>%
   filter(Site == c("M2", "NE", "RP1","RP2", "LM", "LS"))
spacial_df 

#filter by years 2022-2023 = pre fire, 2024-2025 = post fire 
spacial_pre_fire <- spacial_df%>%
  filter(Year >= 2022 & Year <= 2023 )
spacial_pre_fire
unique(spacial_pre_fire$Year)

spacial_post_fire <-spacial_df%>%
  filter(Year >= 2024 & Year <= 2025)
spacial_post_fire


#44.27913	-122.1516
#pre-fire filter(Year >= 2022 & Year <= 2023 )
#post-fire  filter(Year >= 2024 & Year <= 2025)

# SITE WE WANT POST FIRE -> M2, NE, RP1,RP2, LM, LS

```

```{r}
#making new data frame for plants from clean_spec.net, include everything related to plants, drop otherwise. 
#then make pre and post df for plants 

plant_df <- data_frame(clean_spec.net)%>%
  select("Site", "SampleRound", "Year","PlantGenusSpecies","Lat", "Long","non_native_plant")%>%
  filter(non_native_plant== "non-native")%>%

print(plant_df)

#do we/should we sort by site at this point?
#unique(plant_df$Site)
#"CPB" "LS"  "NE"  "RP2" "CPM" "RP1" ### maybe burned sites 

# SITE WE WANT POST FIRE -> M2, NE, RP1,RP2, LM, LS


```

```{r}
pol_df <- data_frame(clean_spec.net) %>%
  select("Site","SampleRound", "Year", "GenusSpecies", "species.strength", "d", "rare.degree", "SiteBeeAbundance", "SiteBeeRichness", "SiteBeeDiversity", "Lat", "Long", "non_native_bee") %>%
  filter(non_native_plant== "non-native")
```


```{r}
#group by - site, year, sampling round ...
clean_spec.net  %>%
  group_by(Site, Year, SampleRound, non_native_bee="non-native" )%>%
  summarize(BeeAbundance = n()
            )
#must use function with summarize 
```

```{r}
#AB testing - ave abund over the year for plants
#ave of sampling round of abund 
#AB test would shuffle ave abund of years of pre and post 
```


```{r}
# then calculate abund and diversity (already calced, just sum and show)
species_interact <- clean_spec.net%>%
  select("GenusSpecies", "PollRichness","PollAbundance","PollDiversity", "Site")%>%
  print()

```


```{r}
# use unique site data -> select and drop all not need col 
  unique(clean_spec.net$Site)
# unique () to create data set 
#Species data set - site, year, sampling round, diversity, abund, rareified richness(rawrB richness), shannons index (H2), simpsons diversity
 #---- # do this for spec.net then veg...
  
# - spec interaction-> WANT col 62 ="degree", 64 = "species.strength" 81 = "d" 84 = "rare.degree", 125 =  "SiteBeeAbundance" 126 = "SiteBeeRichness", 127=  "SiteBeeDiversity" 149 = "PollRichness" 150 = "PollAbundance" 151 = "PollDiversity", 157 = "VegAbundance", 158 = "VegRichness",  159 = "VegDiversity"


```


```{r}
#filter by years 2022-2023 = pre fire, 2024-2025 = post fire 

#pre
filter(Year >= 2022 & Year <= 2023 )
#post
filter(Year >= 2024 & Year <= 2025)
```

```{r}
#make df, pre and post -> join onto unique site data set 
```


```{r}
#design simulation -> AB test, once for poll and once for plants (randomization is the same??
```


```{r}
#netowrk colored by native/nonnative pre and post 

```

