---
title: "LitReview_and_Workflow"
output: html_document
date: "2025-11-14"
Bibliography: "BibTex_references.bib"
---

# Literature Review

Rising global temperatures are forcing the Cascade region of Oregon into a Mediterranean climate where arid, hot summers dry out local vegetation and make the environment susceptible to intense fires. (Halofsky et al., 2020) Non-native species such as Rumex acetosella, Hypericum perforatum, and Senecio vulgaris are not fire adapted which makes them more likely to burn at a fast rate. When grown clustered together, continuous fuel is left for potential fires to burn through. According to research done at the HJ Andrews Experimental Forest, the 2023 Lookout Fire burned roughly 25,659 acres of fuel. Although the fire was not man-made, the combination of changing climate and continuous fuel gave way to one of the largest recent fires in the region. As described by generations of Traditional Ecological Knowledge, many native plant species like camas and oak trees are fire resistant and subsequently promote the fire cycle. Fire suppression culture has been the cause of countless wildfires, but native species regeneration could be the key to mitigating that risk as well as promoting biodiversity.

HJ Andrews experimental forest houses decades of data surrounding old growth forests, meadows, species interactions, phenology, and many more areas of study. Raw data was collected by Dr. Lauren Ponisio and her lab team between the years 2022 and 2025. Observations were collected into two datasets: veg.Rdata (plant species) and spec_net.Rdata (pollinator species) which we will be using to analyze our hypothesis.

Xinyu Li’s dissertation (2024) examined the post-fire vegetation Recovery and Plant-Pollinator Interactions in Southern California Ecosystem and concluded that fire caused an evidence shift in costal environment composition to make way for more flowering plants. After fire, there was an increase in flower abundance and diversity and impacted the pollinator population in the same way. There is strong evidence proving our hypothesis in the southern California environment but now we’d like to use similar methodologies to examine this issue in the meadows of Oregon.

The lookout fire occurred on Aug 5 2023 so any data after that for that year does not exist . To supplement limited 2023 data, will be using the 2022 data as well in the ‘pre-fire’ category. We will also be using years 2024 and 2025 as our ‘post-fire’ category, all with the “veg” data set. The [spec.net](http://spec.net/) data is limited up to \*\*\_ of 2025 because not all of the pollinator species have been identified yet.

Our purpose is to see how landscape composition, specifically meadows, change at the hand of fire and how this effects biodiversity of the region. As seen in Yaekle et al 2014, a larger amount of biodiversity yield more redundancy in ecological niches and this a more stable ecosystem overall. There is evidence of fire improving conditions for bee habitat success. (Burkle et al., 2019) This study aims to understand how landscapes rebuild themselves after disturbances in order to instill practices that will suit their organic regeneration. We will compare plant composition of meadow sites before and after the Lookout Fire to investigate its process of regeneration to see if fire promotes higher levels of plant and bee biodiversity.

Our research questions are: How does the interaction between abundance/species riches of meadows and fire regime modulate the recovery of pollinator and plant biodiversity in post-fire meadow habitats? And, how do changes in plant community composition and floral trait diversity following fires affect the composition of pollinator communities? Our null hypothesis is: Fire does not affect native and invasive plant/bee species composition post-fire and our alternative hypothesis is: Fire perpetuates native species turnover post-fire by clearing invasive and fire-vulnerable species

# Dataset Identification

Dataset A (veg.Rdata) is collected by the Poniso lab within the HJ Andrews experimental forest, specifically meadow plots. The team counted stocks and counted the blooms of each stock for estimate of floral abundance
Dataset B (spec_net.Rdata) is also collected by the Poniso lab in the same location. This time the team woudl observe certain points for fifteen minutesand notes down everytime an interaction took place. Additionally they collected live samples via bee net that were to later be taxonomically identified
Finally, we will be using satellite images of the meadow locations to compare pre and post fire looking for visually scorched areas differences by using lat/long from spec_net data.

All of this data will be catagorized as pre-fire (2022-2023) and post fire (2024-2025). The known holes in [spec.net](http://spec.net/) is that 2025 is incomplete for pollinator identification so we will using what is available. The 2024 sampling year for both data sets is incomplete with the Lookout fire occurring in Auguest 2024 so we will be using veg 2024 data up to the the day of the fire.

# Workflow Plan

## “[spec.net](http://spec.net/)”

With our spec_net data we will refine our data by separating selected species from total data set. We are identifying native pollinators as “Bombus mixus”, “Osmia”, and “Colletes simulans" and non native pollinators as "Apis Mellifera”.

Additionally we will filter the large data set to fit our project by droping colums 47-61 and 85-148. However, we will be using columns 62-84 as that is the species interaction data we are interested in. We also will preserve columns with "VegAbundance", "VegRichness", and "VegDiversity", "PollAbundance", "PollRichness", and "PollDiversity"   for later analysis. Finally we will also be using column 37 and 38 as "Lat" and "Long" data for our spacial data analysis.

## “veg"

We will filter the veg data simularlly as we did [spec.net](http://spec.net/). We identified the native plant species for our project as “Achillea millefolium”, “Lupinus laxiflorus”, “Phacelia hastata" and our non-native species as “Rumex acetosella”, “Hypericum perforatum”, “Senecio vulgaris". Additionally we are intersted in

### Aggregations/derivations:

We will be calculating the floural (veg) and pollinator ([spec.net](http://spec.net/)) abundance for native and non-native, for pre and post fire. Then we will compare them to eachother to see if abundance changed

### Functions/loops (inputs → outputs):

We will want to use loops or functions to create plot to generate plot for pre and post fire veg and pollinator diversity to then compare.

### Statistical test + programmatic implementation:

We want to use AB testing for a veg data  using data→ “vegdiversity”, “vegricheness”, vegabundance”. Then we'll create a group with column 1 being pre fire and column 2 being post fire. Then we'll randomize two columns (~1000 times) and see if B diversity changes and is different from the null. If it is different from null then there IS significant change in meadow composition pre and post fire.

Also, we will create interaction data to compare pre and post fire by using our previous calculated abundances. Then we'll create a network and calculate diversity.

Finally, we want to use the lat/long data from spec.net to overlay onto satellite imagery of our meadows to show changes pre and post fire.

### Planned visualizations/tables: …

We will visualize the distribution of random vs observed with the null as a histogram and add a line to equal observed value. We will visualize our calculated network of picked pollinator interactions. We will visualize the pre and post fire data with our spatial data. Lastly we will visualize a summary of plant species abundance pre and post fire with a bar plot
